### PR TITLE
Respect cache OPTIONS settings. Fixes Issue #13

### PR DESCRIPTION
**Pull request by petersanchez**
This resolves the issue #13 issue with OPTIONS.

Also includes code from Pull Request #11. Also addresses de-serialization issues mentioned in issue #12.

### CODE REVIEW

**Comment by jamescarr** [comment]
Is this project dead? PR has been open since April!

**Comment by petersanchez** [comment]
@jamescarr Seems that way. I've been working from my own personal fork since this PR was filed.

**Comment by jamescarr** [comment]
@petersanchez heh, in that case I may fork , backfill your commits and release a new package. We're actually re-working this now to use Pinterest's [pymemcache](https://github.com/pinterest/pymemcache) library so it's quite different. 

How has this faired in production? I'll be doing some perf tests this week.

**Comment by petersanchez** [comment]
@jamescarr I'm using it in production for a client who has ample traffic to the environment. So far, so good. Keep me posted on the new package please.

**Comment by mattlong** [comment]
@jamescarr @petersanchez I just stumbled across this and am quite interested in using it (or any forks out there) in production. Any pointers or gotchas?

**Comment by petersanchez** [comment]
@mattlong I'm using it in prod and it's fine. No real gotchas. Just plug it in, piece of cake.

**Comment by mattlong** [comment]
@jamescarr I'm finally actually in the process of switching to this. You mentioned working on a version using Pinterest's pymemcache. If it's not already, is that something you could make available?

**Pull request closed without merging**
